from huginn import __version__

# Substitua o conteúdo abaixo pela sua arte ASCII.
ASCII_ART = r"""
+----------------------------------------------------------------------------+
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMM0lolNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMNNWWk:;;dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMolNo;,;:okNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMN:;:',',;,,KMW0XMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMWk,,.,,;;;clWKocKMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMWc,',;:;:ccdOl:kWW0d0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMWNWx,,,:;;;;:;:llxWXo:cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMXNNc;,;cc;;:;'cldNklc:dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMWWW0',,::;;,c::ccdlllcxNMWMMMMMMMMMMMMMMMMMMMMMXXW0olNMMMMMMMM|
|MMMMMMMMMMMMMMMMMd':;:;c:,;;;,':cclKWKk0WMMMMMMMMMMMMMMMMMMXl,l:''oWMMMMMMMM|
|MMMMMMMMMMMMMMMMW:::;,:c;;,'.';:;ckxdlxWMMMMMMMMMMMMMMMMMWk;'',''oWMMMMMMMMM|
|MMMMMMMMMMMMMMMM0';;,:c::;:,.,;;;ccolxWMMMMMMMMMMMMMMMWNx;'..'''lKWMMMMMMMMM|
|MMMMMMMMMMMMMMMMd,;;;;,,;cc;',,:llclKMMMMMMMMMMMMMMMMNx,''...''lNNWMMMMMMMMM|
|MMMMMMMMMMMMMMMMl;:;,,,;ccc;,,;cccxNX0KMMMMMMMMMMMMM0;.'......;OkkWMMMMMMMMM|
|MMMMMMMMMMMMMMMK,;;,,';::::::c:c:dxdlxNMMMMMMMMMMMNo'''..'....,':KWMMMMMMMMM|
|MMMMMMMMMMMMMMMo,',,,,;:;;:;::,;:cld0WMMMMMMMMMMMO;....''......'oNWMMMMMMMMM|
|MMMMMMMMMMMMMMWc;',;;;;;;;;:::;:::l0MMMMMMMMMMMWo''''''.....''cKMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMk;;,,,;,,;;,',,,,;::lxXWMMMMMMWO;............,d0WMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMk;:,,,,,;:;;:;;::;:cokNMMWWKl,.......''....'cd0WMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMW0c;;,'';:;,'';:;,;,cOXWW0c...............':dWMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMNo;;'',,,,'.';,,;:ccll,.................'dXMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMK;:,',;;;;;;;,,,;:l'   .............';;c0MMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMW:;,',;;;;;;;,,::;:'   ............,,lKWMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMN0xdxo:',',,,,,,,,''',',;,.  ...........:d0WWMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMWOc.......''''''',;;,,,'',,;'      ........,xWMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMNx,.........'''.',,,,;;;;,'';;'.     ...,odkKXNMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMX,...........'.'''',,,,,,,,;;;'.......,,;:XMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMX,.'...','...''...'..'''',',;;::;...''.lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMd..';...',...',..........',',;;,...';,,..lXMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMk...'..',,...',....................';;,,...oKMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMW:''...''..:..'''.''',,'.''.......,;;,,'..'',lOWMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMW;.....;dd0Wd'......',,,,'''.......''',,,,,::;..oXMWWMMMMMMMMMMMMMMMMM|
|MMMMMMMl ...OWMMMMMXkl.'. ...'''''',......',..,,...... .:OWMMMMMMMMMMMMMMMMM|
|MMMMMMMX..;XMMMMMMMMWWxxXK0OOd,.','''....'.....'...''.,.. 'dNMMMMMMMMMMMMMMM|
|MMMMMMMMx.oMMMMMMMMMMMMWNNMMMMNo',,,,'..  ...','''...,,,,'...c0WMMMMMMMMMMMM|
|MMMMMMMMWk0MMMMMMMMMMMMMMMMMMMMWo.',,'...........,;,'',,,,,'...,dXMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc....dXo .  ......',,,'...';;'.:'lXMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk...xWMx .:kXxo'.....,,,,,'..,;cdxkWMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo .kWMW,.xWMWKX0;........',,'..',ckNMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.'0MWWo.0MMMMMMMXl'..''..c,....''';cOMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl'K0x,,.xMMMMMMMMMMO;..c:,;OOo;',;,',,OWMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.0k...c.OMMMMMMMMMMMWOooKOkoXMWXkoc;,,;XMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMKx0O':Wc.xod,kMMMMMMMMMMMMMWWWWMWMMMMMMWXko:;xWMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMx.  .;'xKcxNOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWN0xNMM|
|MMMMMMMMMMMMMMMMMMMMMMMMW0'l.c0x;dWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMWNXd;lN0kXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMM0oKMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
|dxkO0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|
+----------------------------------------------------------------------------+
"""

TAGLINE = "reconhecimento passivo & ativo para pentest"


def show():
    print(ASCII_ART)
    print(f"  huginn v{__version__} — {TAGLINE}")
    print()
